name: Build
on: push

jobs:
    build:
        runs-on: macos-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
              with:
                repository: corpnewt/gibMacOS
            - run: |
                  python3 gibMacOS.command --latest
                  python3 BuildmacOSInstallApp.command << $(find 'macOS Downloads' -type d | tail -1)
