name: Build
on: push

jobs:
    build:
        runs-on: macos-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - run: |
                  python .github/workflows/mem1.py
                  pwd
                  df -H