name: Build
on: push

jobs:
    build:
        runs-on: windows-latest
        steps:
            - shell: powershell
              run: |
                get-wmiobject win32_processor | select-object NumberOfCores, NumberOfLogicalProcessors
                (Get-CimInstance Win32_PhysicalMemory | Measure-Object -Property capacity -Sum).sum /1gb